### ISSUE TITLE
Long cold start of Cloud Run

### ISSUE THREAD

**Issue by stahn** [AdnanHodzic/wp-cloud-run#1]
Hi, one of the benefits of Cloud Run is that it scales down to 0. For larger containers like Wordpress (entire LAMP stack) there can a significant cold start, is this solution addressing it?

**Comment by AdnanHodzic** [comment]
Absolutely, I talk about it in [4 - Create wp-cloud-run: WordPress Cloud Run service](https://www.youtube.com/watch?v=BleYRQBg7pA) video ([exact timestamp](https://youtu.be/BleYRQBg7pA?si=ZFxSDu7tyzxX_o1i&t=145)).

But I recommend you watch the whole [wp-cloud-run: Ultimate WordPress setup on (GCP) Cloud Run playlist](https://www.youtube.com/playlist?list=PL83G0TLSeXREwjHDZPsV_34azAmniL81V), as big part of it will be done in [8.3 – WordPress performance improvements with Cloudflare free plan, CDN, & caching for optimization](https://youtu.be/CLOCCFT8rRo?si=iImTC48A50bXJlvr)

Closing the issue since it's not an actual issue, but more of a discussion point :)
